services:
  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - my_network

  php:
    build:
      context: .
      dockerfile: config/php/Dockerfile
    platform: linux/amd64
    container_name: yii2-php
    volumes:
      - ./app:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    networks:
      - my_network
    command: >
      bash -c "chmod -R 775 /var/www/html && php-fpm"

  mysql:
    build:
      context: .
      dockerfile: config/mysql/Dockerfile
    container_name: my-mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    ports:
      - "8888:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 256M
    depends_on:
      - mysql
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
