version: "3"

services:
  nginx:
    image: nginx:stable
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
    volumes:
      - ./www:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - my_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php:
    build:
      context: ./config/${PHPVERSION}
    platform: linux/amd64
    container_name: "${COMPOSE_PROJECT_NAME}-${PHPVERSION}"
    volumes:
      - ./www:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    networks:
      - my_network
    command: >
      bash -c "chmod -R 775 /var/www/html && php-fpm"

  mysql:
    build:
      context: "./config/${DATABASE}" 
    container_name: "${COMPOSE_PROJECT_NAME}-${DATABASE}"
    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    ports:
      - "${HOST_MACHINE_PMA_PORT}:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
    depends_on:
      - mysql
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
