FROM mysql:8.0

# คัดลอกไฟล์ my.cnf (optional)
# COPY my.cnf /etc/mysql/conf.d/my.cnf

# คัดลอก SQL สำหรับ init (optional)
# COPY init.sql /docker-entrypoint-initdb.d/init.sql

# กำหนดสิทธิ์ไฟล์ config
# RUN chmod 644 /etc/mysql/conf.d/my.cnf
